In [1]:
import glob
import os
import pandas as pd

In [2]:
players = pd.read_csv('./players.csv')

In [3]:
players.head()

,#Date/Time of Update: 2017-05-09 4:34:01 PM,#Player ID,#LastName,#FirstName,#Jersey Num,#Position,#Height,#Weight,#Birth Date,#Age,...,#Team Abbr,#Team City,#Team Name,#GamesPlayed,#Fg2PtAtt,#Fg2PtMade,#Fg3PtAtt,#Fg3PtMade,#FtAtt,#FtMade
0,NaN,10138,Abrines,Alex,8.0,F,"6'6""",190.0,8/1/1993,23.0,...,OKL,Oklahoma City,Thunder,73,94,40,247,94,49,44
1,NaN,9466,Acy,Quincy,4.0,PF,"6'7""",240.0,10/6/1990,26.0,...,BRO,Brooklyn,Nets,46,80,33,90,37,60,45
2,NaN,9390,Adams,Steven,12.0,C,"7'0""",255.0,7/20/1993,23.0,...,OKL,Oklahoma City,Thunder,81,652,374,2,0,257,157
3,NaN,9375,Afflalo,Arron,40.0,SG,"6'5""",215.0,10/15/1985,31.0,...,SAC,Sacramento,Kings,71,269,123,151,62,93,83
4,NaN,9357,Ajinca,Alexis,42.0,C,"7'2""",248.0,5/6/1988,29.0,...,NOP,New Orleans,Pelicans,55,174,89,4,0,40,29

In [4]:
players = players.iloc[:,1:]

In [5]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 23 columns):
#Player ID        517 non-null int64
#LastName         517 non-null object
#FirstName        517 non-null object
#Jersey Num       493 non-null float64
#Position         517 non-null object
#Height           510 non-null object
#Weight           510 non-null float64
#Birth Date       508 non-null object
#Age              508 non-null float64
#Birth City       219 non-null object
#Birth Country    228 non-null object
#Rookie           517 non-null object
#Team ID          517 non-null int64
#Team Abbr        517 non-null object
#Team City        517 non-null object
#Team Name        517 non-null object
#GamesPlayed      517 non-null int64
#Fg2PtAtt         517 non-null int64
#Fg2PtMade        517 non-null int64
#Fg3PtAtt         517 non-null int64
#Fg3PtMade        517 non-null int64
#FtAtt            517 non-null int64
#FtMade           517 non-null int64
dtypes: float64(3), int64(9), object(11)
memory usage: 93.0+ KB

In [6]:
players['full_name'] = players['#FirstName'] + " " + players['#LastName']

In [7]:
players.drop(['#FirstName','#LastName'],axis=1,inplace=True)

In [8]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 22 columns):
#Player ID        517 non-null int64
#Jersey Num       493 non-null float64
#Position         517 non-null object
#Height           510 non-null object
#Weight           510 non-null float64
#Birth Date       508 non-null object
#Age              508 non-null float64
#Birth City       219 non-null object
#Birth Country    228 non-null object
#Rookie           517 non-null object
#Team ID          517 non-null int64
#Team Abbr        517 non-null object
#Team City        517 non-null object
#Team Name        517 non-null object
#GamesPlayed      517 non-null int64
#Fg2PtAtt         517 non-null int64
#Fg2PtMade        517 non-null int64
#Fg3PtAtt         517 non-null int64
#Fg3PtMade        517 non-null int64
#FtAtt            517 non-null int64
#FtMade           517 non-null int64
full_name         517 non-null object
dtypes: float64(3), int64(9), object(10)
memory usage: 88.9+ KB

In [9]:
players.rename(columns={
    '#Player ID':'player_id',
    '#Jersey Num':'jersey_number',
    '#Position':'position',
    '#Height':'height',
    '#Weight':'weight',
    '#Age':'age',
    '#Birth Date':'birthdate',
    '#Birth City':'birth_city',
    '#Birth Country':'birth_country',
    '#Rookie':'rookie',
    '#Team ID':'team_id',
    '#Team Abbr':'team_abbr',
    '#Team City':'team_city',
    '#Team Name':'team_name',
    '#GamesPlayed':'games_played',
    '#Fg2PtAtt':'fg2_pt_att',
    '#Fg2PtMade':'fg2_pt_made',
    '#Fg3PtAtt':'fg3_pt_att',
    '#Fg3PtMade':'fg3_pt_made',
    '#FtAtt':'ft_att',
    '#FtMade':'ft_made',
},inplace=True)

In [13]:
players

,jersey_number,position,height,weight,birthdate,age,birth_city,birth_country,rookie,team_id,...,team_city,team_name,games_played,fg2_pt_att,fg2_pt_made,fg3_pt_att,fg3_pt_made,ft_att,ft_made,full_name
player_id,,,,,,,,,,,,,,,,,,,,,
10138,8.0,F,"6'6""",190.0,8/1/1993,23.0,Palma de Mallorca,Spain,Y,96,...,Oklahoma City,Thunder,73,94,40,247,94,49,44,Alex Abrines
9466,4.0,PF,"6'7""",240.0,10/6/1990,26.0,"Tyler, TX",USA,N,84,...,Brooklyn,Nets,46,80,33,90,37,60,45,Quincy Acy
9390,12.0,C,"7'0""",255.0,7/20/1993,23.0,Rotorua,NewZealand,N,96,...,Oklahoma City,Thunder,81,652,374,2,0,257,157,Steven Adams
9375,40.0,SG,"6'5""",215.0,10/15/1985,31.0,"Los Angeles, CA",USA,N,103,...,Sacramento,Kings,71,269,123,151,62,93,83,Arron Afflalo
9357,42.0,C,"7'2""",248.0,5/6/1988,29.0,Saint-?tienne,France,N,110,...,New Orleans,Pelicans,55,174,89,4,0,40,29,Alexis Ajinca
9272,45.0,C,"6'11""",245.0,10/31/1988,28.0,"Burnsville, MN",USA,N,100,...,Minnesota,Timberwolves,72,86,45,0,0,22,15,Cole Aldrich
9480,12.0,PF,"6'11""",240.0,7/19/1985,31.0,"Dallas, TX",USA,N,106,...,San Antonio,Spurs,81,993,477,56,23,271,220,LaMarcus Aldridge
9454,34.0,PF,"6'8""",245.0,11/15/1995,21.0,"Chicago, IL",USA,N,95,...,Orlando,Magic,1,0,0,0,0,0,0,Cliff Alexander
9254,5.0,PF,"6'9""",255.0,2/4/1989,28.0,NaN,NaN,N,87,...,Indiana,Pacers,73,167,77,1,0,33,23,Lavoy Allen
9299,9.0,SG,"6'4""",213.0,1/11/1982,35.0,"Chicago, IL",USA,N,107,...,Memphis,Grizzlies,77,541,259,54,15,130,80,Tony Allen
9452,8.0,SF,"6'9""",215.0,9/21/1990,26.0,"Atlanta, GA",USA,N,97,...,Portland,Trail Blazers,67,253,113,213,70,136,96,Al-Farouq Aminu
9297,7.0,C,"6'10""",245.0,7/6/1978,38.0,"Lola, TX",USA,N,86,...,Cleveland,Cavaliers,20,19,9,3,0,14,10,Chris Andersen
9527,26.0,SG,"6'6""",220.0,10/16/1982,34.0,"Minneapolis, MN",USA,N,102,...,Los Angeles,Clippers,46,36,16,44,14,16,12,Alan Anderson
9469,5.0,SG,"6'6""",213.0,3/25/1989,28.0,"El Dorado, AR",USA,N,103,...,Sacramento,Kings,1,0,0,0,0,0,0,James Anderson
9178,1.0,SF,"6'6""",228.0,11/18/1993,23.0,"Montross, VA",USA,N,85,...,Philadelphia,76ers,81,243,128,193,58,129,102,Justin Anderson
9475,1.0,SF,"6'9""",230.0,9/20/1993,23.0,"New York, NY",USA,N,106,...,San Antonio,Spurs,81,169,78,40,15,57,45,Kyle Anderson
9353,36.0,PF,"6'10""",240.0,5/6/1988,29.0,"Sacramento, CA",USA,N,109,...,Houston,Rockets,76,266,119,507,205,150,129,Ryan Anderson
9325,34.0,PG,"6'11""",222.0,12/6/1994,22.0,Athens,Greece,N,90,...,Milwaukee,Bucks,82,1077,607,180,49,612,471,Giannis Antetokounmpo
9560,43.0,SF,"6'7""",205.0,7/18/1992,24.0,Rost,Greece,N,83,...,New York,Knicks,1,0,0,0,0,0,0,Thanasis Antetokounmpo
9369,7.0,SF,"6'8""",240.0,5/29/1984,32.0,"Brooklyn, NY",USA,N,83,...,New York,Knicks,79,970,451,420,151,365,304,Carmelo Anthony
9214,50.0,C,"6'9""",245.0,8/9/1982,34.0,"Montreal, QC",Canada,N,106,...,San Antonio,Spurs,28,16,10,0,0,8,5,Joel Anthony
9235,1.0,SF,"6'8""",215.0,6/30/1985,31.0,NaN,NaN,N,109,...,Houston,Rockets,82,243,136,554,190,126,93,Trevor Ariza
9198,0.0,PF,"6'9""",235.0,3/25/1988,29.0,NaN,NaN,N,99,...,Denver,Nuggets,55,98,42,117,53,22,19,Darrell Arthur
9358,3.0,C,"7'0""",255.0,7/4/1986,30.0,NaN,NaN,N,110,...,New Orleans,Pelicans,38,65,31,0,0,39,23,Omer Asik
9190,12.0,PG,"6'0""",183.0,11/10/1987,29.0,"New Orleans, LA",USA,N,95,...,Orlando,Magic,82,243,100,274,95,161,131,D.J. Augustin
9276,19.0,C,"6'9""",240.0,4/29/1987,30.0,NaN,NaN,N,102,...,Los Angeles,Clippers,1,0,0,0,0,0,0,Jeff Ayres
9360,5.0,SF,"6'9""",217.0,6/20/1989,27.0,"Cincinnati, OH",USA,N,92,...,Miami,Heat,77,71,26,210,87,15,11,Luke Babbitt
10102,31.0,G,"6'4""",220.0,3/30/1993,24.0,NaN,NaN,Y,83,...,New York,Knicks,66,132,59,85,23,43,28,Ron Baker
10131,4.0,G,"6'4""",202.0,3/29/1996,21.0,NaN,NaN,Y,107,...,Memphis,Grizzlies,42,92,33,22,3,37,31,Wade Baldwin IV
9229,19.0,SG,"6'3""",194.0,11/28/1982,34.0,Sao Paulo,Brazil,N,104,...,Phoenix,Suns,72,295,137,98,35,45,40,Leandro Barbosa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9312,21.0,C,"7'0""",265.0,6/13/1989,27.0,NaN,NaN,N,92,...,Miami,Heat,80,973,542,0,0,358,225,Hassan Whiteside
9259,42.0,PF,"6'11""",250.0,3/27/1991,26.0,NaN,NaN,N,87,...,Indiana,Pacers,1,0,0,0,0,0,0,Shayne Whittington
9342,22.0,SF,"6'8""",199.0,2/23/1995,22.0,NaN,NaN,N,100,...,Minnesota,Timberwolves,82,1279,606,289,103,542,412,Andrew Wiggins
9266,30.0,SG,"6'5""",195.0,12/30/1990,26.0,"Pleasant Grove, UT",USA,N,95,...,Orlando,Magic,38,16,5,15,3,2,2,CJ Wilcox
9441,15.0,PF,"6'8""",260.0,1/28/1993,24.0,NaN,NaN,N,104,...,Phoenix,Suns,63,266,138,1,0,112,70,Alan Williams
9184,8.0,PG,"6'3""",200.0,6/26/1984,32.0,NaN,NaN,N,86,...,Cleveland,Cavaliers,68,366,178,234,85,109,90,Deron Williams
9377,22.0,SF,"6'8""",240.0,5/25/1991,25.0,"Bellflower, CA",USA,N,86,...,Cleveland,Cavaliers,69,147,78,97,30,89,58,Derrick Williams
9557,NaN,SG,"6'5""",183.0,6/20/1989,27.0,"Memphis, TN",USA,N,107,...,Memphis,Grizzlies,14,8,4,4,2,4,0,Elliott Williams
9287,23.0,SG,"6'1""",175.0,10/26/1986,30.0,NaN,NaN,N,109,...,Houston,Rockets,81,553,264,445,163,457,402,Lou Williams
11652,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,Y,109,...,Houston,Rockets,1,0,0,0,0,0,0,M Williams
9134,2.0,PF,"6'9""",237.0,6/19/1986,30.0,NaN,NaN,N,93,...,Charlotte,Hornets,77,350,173,353,124,150,131,Marvin Williams
11546,5.0,F,"6'6""",205.0,9/13/1986,30.0,NaN,USA,N,110,...,New Orleans,Pelicans,9,12,3,11,5,7,6,Reggie Williams
11414,10.0,F,"6'7""",210.0,12/30/1994,22.0,NaN,NaN,Y,109,...,Houston,Rockets,28,96,51,58,16,28,21,Troy Williams
10148,30.0,F,"6'10""",240.0,10/20/1992,24.0,NaN,NaN,Y,109,...,Houston,Rockets,26,1,0,13,4,2,1,Kyle Wiltjer
9313,20.0,SF,"6'7""",225.0,3/26/1996,21.0,NaN,NaN,N,92,...,Miami,Heat,24,191,73,35,7,47,29,Justise Winslow
9516,24.0,C,"7'0""",231.0,3/7/1990,27.0,NaN,NaN,N,98,...,Utah,Jazz,67,102,55,1,0,48,36,Jeff Withey
9427,35.0,PF,"6'11""",220.0,9/27/1995,21.0,"Long Beach, CA",USA,N,93,...,Charlotte,Hornets,23,18,12,5,0,15,11,Christian Wood
9291,37.0,SF,"6'7""",260.0,11/13/1979,37.0,"St. John's, NY",USA,N,105,...,Los Angeles,Lakers,43,30,10,38,9,16,10,Metta World Peace
9304,34.0,PF,"6'10""",210.0,10/5/1987,29.0,NaN,NaN,N,107,...,Memphis,Grizzlies,33,134,83,1,0,35,23,Brandan Wright
9495,55.0,PG,"6'5""",190.0,4/26/1992,25.0,NaN,NaN,N,81,...,Toronto,Raptors,27,85,39,30,10,55,42,Delon Wright
9383,5.0,G,"6'6""",205.0,4/12/1993,24.0,"Renton, WA",USA,N,107,...,Memphis,Grizzlies,1,0,0,0,0,0,0,Tony Wroten
9103,13.0,SG,"6'6""",215.0,8/16/1995,21.0,NaN,NaN,N,82,...,Boston,Celtics,40,23,13,35,12,9,6,James Young
9260,1.0,PG,"6'2""",180.0,6/27/1992,24.0,NaN,NaN,N,87,...,Indiana,Pacers,52,49,21,23,5,15,11,Joe Young
9280,0.0,SG,"6'7""",210.0,6/1/1985,31.0,NaN,NaN,N,105,...,Los Angeles,Lakers,64,212,102,420,170,90,77,Nick Young
9119,30.0,PF,"6'8""",220.0,6/21/1988,28.0,"New Orleans, LA",USA,N,87,...,Indiana,Pacers,75,569,317,118,45,86,45,Thaddeus Young
9130,40.0,C,"7'0""",240.0,10/5/1992,24.0,NaN,NaN,N,93,...,Charlotte,Hornets,67,442,253,1,0,196,133,Cody Zeller
9099,44.0,C,"7'0""",253.0,1/17/1990,27.0,NaN,NaN,N,82,...,Boston,Celtics,68,157,78,1,0,39,22,Tyler Zeller
10163,33.0,C,"7'0""",240.0,9/9/1996,20.0,NaN,NaN,Y,95,...,Orlando,Magic,31,31,10,0,0,5,3,Stephen Zimmerman
10158,16.0,F,"6'8""",210.0,2/18/1994,23.0,NaN,NaN,Y,89,...,Chicago,Bulls,55,122,55,99,33,40,31,Paul Zipser
10169,40.0,C,"7'1""",265.0,3/17/1997,20.0,NaN,NaN,Y,105,...,Los Angeles,Lakers,47,235,126,3,0,49,32,Ivica Zubac

In [11]:
players.set_index('player_id',inplace=True)

In [12]:
players.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 517 entries, 10138 to 10169
Data columns (total 21 columns):
jersey_number    493 non-null float64
position         517 non-null object
height           510 non-null object
weight           510 non-null float64
birthdate        508 non-null object
age              508 non-null float64
birth_city       219 non-null object
birth_country    228 non-null object
rookie           517 non-null object
team_id          517 non-null int64
team_abbr        517 non-null object
team_city        517 non-null object
team_name        517 non-null object
games_played     517 non-null int64
fg2_pt_att       517 non-null int64
fg2_pt_made      517 non-null int64
fg3_pt_att       517 non-null int64
fg3_pt_made      517 non-null int64
ft_att           517 non-null int64
ft_made          517 non-null int64
full_name        517 non-null object
dtypes: float64(3), int64(8), object(10)
memory usage: 88.9+ KB

In [15]:
players.head()

,jersey_number,position,height,weight,birthdate,age,birth_city,birth_country,rookie,team_id,...,team_city,team_name,games_played,fg2_pt_att,fg2_pt_made,fg3_pt_att,fg3_pt_made,ft_att,ft_made,full_name
player_id,,,,,,,,,,,,,,,,,,,,,
10138,8.0,F,"6'6""",190.0,8/1/1993,23.0,Palma de Mallorca,Spain,Y,96,...,Oklahoma City,Thunder,73,94,40,247,94,49,44,Alex Abrines
9466,4.0,PF,"6'7""",240.0,10/6/1990,26.0,"Tyler, TX",USA,N,84,...,Brooklyn,Nets,46,80,33,90,37,60,45,Quincy Acy
9390,12.0,C,"7'0""",255.0,7/20/1993,23.0,Rotorua,NewZealand,N,96,...,Oklahoma City,Thunder,81,652,374,2,0,257,157,Steven Adams
9375,40.0,SG,"6'5""",215.0,10/15/1985,31.0,"Los Angeles, CA",USA,N,103,...,Sacramento,Kings,71,269,123,151,62,93,83,Arron Afflalo
9357,42.0,C,"7'2""",248.0,5/6/1988,29.0,Saint-?tienne,France,N,110,...,New Orleans,Pelicans,55,174,89,4,0,40,29,Alexis Ajinca

In [16]:
players.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 517 entries, 10138 to 10169
Data columns (total 21 columns):
jersey_number    493 non-null float64
position         517 non-null object
height           510 non-null object
weight           510 non-null float64
birthdate        508 non-null object
age              508 non-null float64
birth_city       219 non-null object
birth_country    228 non-null object
rookie           517 non-null object
team_id          517 non-null int64
team_abbr        517 non-null object
team_city        517 non-null object
team_name        517 non-null object
games_played     517 non-null int64
fg2_pt_att       517 non-null int64
fg2_pt_made      517 non-null int64
fg3_pt_att       517 non-null int64
fg3_pt_made      517 non-null int64
ft_att           517 non-null int64
ft_made          517 non-null int64
full_name        517 non-null object
dtypes: float64(3), int64(8), object(10)
memory usage: 88.9+ KB

In [18]:
players.drop(['height','weight','birth_city','birth_country'],axis=1,inplace=True)

In [19]:
players

,jersey_number,position,birthdate,age,rookie,team_id,team_abbr,team_city,team_name,games_played,fg2_pt_att,fg2_pt_made,fg3_pt_att,fg3_pt_made,ft_att,ft_made,full_name
player_id,,,,,,,,,,,,,,,,,
10138,8.0,F,8/1/1993,23.0,Y,96,OKL,Oklahoma City,Thunder,73,94,40,247,94,49,44,Alex Abrines
9466,4.0,PF,10/6/1990,26.0,N,84,BRO,Brooklyn,Nets,46,80,33,90,37,60,45,Quincy Acy
9390,12.0,C,7/20/1993,23.0,N,96,OKL,Oklahoma City,Thunder,81,652,374,2,0,257,157,Steven Adams
9375,40.0,SG,10/15/1985,31.0,N,103,SAC,Sacramento,Kings,71,269,123,151,62,93,83,Arron Afflalo
9357,42.0,C,5/6/1988,29.0,N,110,NOP,New Orleans,Pelicans,55,174,89,4,0,40,29,Alexis Ajinca
9272,45.0,C,10/31/1988,28.0,N,100,MIN,Minnesota,Timberwolves,72,86,45,0,0,22,15,Cole Aldrich
9480,12.0,PF,7/19/1985,31.0,N,106,SAS,San Antonio,Spurs,81,993,477,56,23,271,220,LaMarcus Aldridge
9454,34.0,PF,11/15/1995,21.0,N,95,ORL,Orlando,Magic,1,0,0,0,0,0,0,Cliff Alexander
9254,5.0,PF,2/4/1989,28.0,N,87,IND,Indiana,Pacers,73,167,77,1,0,33,23,Lavoy Allen
9299,9.0,SG,1/11/1982,35.0,N,107,MEM,Memphis,Grizzlies,77,541,259,54,15,130,80,Tony Allen
9452,8.0,SF,9/21/1990,26.0,N,97,POR,Portland,Trail Blazers,67,253,113,213,70,136,96,Al-Farouq Aminu
9297,7.0,C,7/6/1978,38.0,N,86,CLE,Cleveland,Cavaliers,20,19,9,3,0,14,10,Chris Andersen
9527,26.0,SG,10/16/1982,34.0,N,102,LAC,Los Angeles,Clippers,46,36,16,44,14,16,12,Alan Anderson
9469,5.0,SG,3/25/1989,28.0,N,103,SAC,Sacramento,Kings,1,0,0,0,0,0,0,James Anderson
9178,1.0,SF,11/18/1993,23.0,N,85,PHI,Philadelphia,76ers,81,243,128,193,58,129,102,Justin Anderson
9475,1.0,SF,9/20/1993,23.0,N,106,SAS,San Antonio,Spurs,81,169,78,40,15,57,45,Kyle Anderson
9353,36.0,PF,5/6/1988,29.0,N,109,HOU,Houston,Rockets,76,266,119,507,205,150,129,Ryan Anderson
9325,34.0,PG,12/6/1994,22.0,N,90,MIL,Milwaukee,Bucks,82,1077,607,180,49,612,471,Giannis Antetokounmpo
9560,43.0,SF,7/18/1992,24.0,N,83,NYK,New York,Knicks,1,0,0,0,0,0,0,Thanasis Antetokounmpo
9369,7.0,SF,5/29/1984,32.0,N,83,NYK,New York,Knicks,79,970,451,420,151,365,304,Carmelo Anthony
9214,50.0,C,8/9/1982,34.0,N,106,SAS,San Antonio,Spurs,28,16,10,0,0,8,5,Joel Anthony
9235,1.0,SF,6/30/1985,31.0,N,109,HOU,Houston,Rockets,82,243,136,554,190,126,93,Trevor Ariza
9198,0.0,PF,3/25/1988,29.0,N,99,DEN,Denver,Nuggets,55,98,42,117,53,22,19,Darrell Arthur
9358,3.0,C,7/4/1986,30.0,N,110,NOP,New Orleans,Pelicans,38,65,31,0,0,39,23,Omer Asik
9190,12.0,PG,11/10/1987,29.0,N,95,ORL,Orlando,Magic,82,243,100,274,95,161,131,D.J. Augustin
9276,19.0,C,4/29/1987,30.0,N,102,LAC,Los Angeles,Clippers,1,0,0,0,0,0,0,Jeff Ayres
9360,5.0,SF,6/20/1989,27.0,N,92,MIA,Miami,Heat,77,71,26,210,87,15,11,Luke Babbitt
10102,31.0,G,3/30/1993,24.0,Y,83,NYK,New York,Knicks,66,132,59,85,23,43,28,Ron Baker
10131,4.0,G,3/29/1996,21.0,Y,107,MEM,Memphis,Grizzlies,42,92,33,22,3,37,31,Wade Baldwin IV
9229,19.0,SG,11/28/1982,34.0,N,104,PHX,Phoenix,Suns,72,295,137,98,35,45,40,Leandro Barbosa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9312,21.0,C,6/13/1989,27.0,N,92,MIA,Miami,Heat,80,973,542,0,0,358,225,Hassan Whiteside
9259,42.0,PF,3/27/1991,26.0,N,87,IND,Indiana,Pacers,1,0,0,0,0,0,0,Shayne Whittington
9342,22.0,SF,2/23/1995,22.0,N,100,MIN,Minnesota,Timberwolves,82,1279,606,289,103,542,412,Andrew Wiggins
9266,30.0,SG,12/30/1990,26.0,N,95,ORL,Orlando,Magic,38,16,5,15,3,2,2,CJ Wilcox
9441,15.0,PF,1/28/1993,24.0,N,104,PHX,Phoenix,Suns,63,266,138,1,0,112,70,Alan Williams
9184,8.0,PG,6/26/1984,32.0,N,86,CLE,Cleveland,Cavaliers,68,366,178,234,85,109,90,Deron Williams
9377,22.0,SF,5/25/1991,25.0,N,86,CLE,Cleveland,Cavaliers,69,147,78,97,30,89,58,Derrick Williams
9557,NaN,SG,6/20/1989,27.0,N,107,MEM,Memphis,Grizzlies,14,8,4,4,2,4,0,Elliott Williams
9287,23.0,SG,10/26/1986,30.0,N,109,HOU,Houston,Rockets,81,553,264,445,163,457,402,Lou Williams
11652,NaN,C,NaN,NaN,Y,109,HOU,Houston,Rockets,1,0,0,0,0,0,0,M Williams
9134,2.0,PF,6/19/1986,30.0,N,93,CHA,Charlotte,Hornets,77,350,173,353,124,150,131,Marvin Williams
11546,5.0,F,9/13/1986,30.0,N,110,NOP,New Orleans,Pelicans,9,12,3,11,5,7,6,Reggie Williams
11414,10.0,F,12/30/1994,22.0,Y,109,HOU,Houston,Rockets,28,96,51,58,16,28,21,Troy Williams
10148,30.0,F,10/20/1992,24.0,Y,109,HOU,Houston,Rockets,26,1,0,13,4,2,1,Kyle Wiltjer
9313,20.0,SF,3/26/1996,21.0,N,92,MIA,Miami,Heat,24,191,73,35,7,47,29,Justise Winslow
9516,24.0,C,3/7/1990,27.0,N,98,UTA,Utah,Jazz,67,102,55,1,0,48,36,Jeff Withey
9427,35.0,PF,9/27/1995,21.0,N,93,CHA,Charlotte,Hornets,23,18,12,5,0,15,11,Christian Wood
9291,37.0,SF,11/13/1979,37.0,N,105,LAL,Los Angeles,Lakers,43,30,10,38,9,16,10,Metta World Peace
9304,34.0,PF,10/5/1987,29.0,N,107,MEM,Memphis,Grizzlies,33,134,83,1,0,35,23,Brandan Wright
9495,55.0,PG,4/26/1992,25.0,N,81,TOR,Toronto,Raptors,27,85,39,30,10,55,42,Delon Wright
9383,5.0,G,4/12/1993,24.0,N,107,MEM,Memphis,Grizzlies,1,0,0,0,0,0,0,Tony Wroten
9103,13.0,SG,8/16/1995,21.0,N,82,BOS,Boston,Celtics,40,23,13,35,12,9,6,James Young
9260,1.0,PG,6/27/1992,24.0,N,87,IND,Indiana,Pacers,52,49,21,23,5,15,11,Joe Young
9280,0.0,SG,6/1/1985,31.0,N,105,LAL,Los Angeles,Lakers,64,212,102,420,170,90,77,Nick Young
9119,30.0,PF,6/21/1988,28.0,N,87,IND,Indiana,Pacers,75,569,317,118,45,86,45,Thaddeus Young
9130,40.0,C,10/5/1992,24.0,N,93,CHA,Charlotte,Hornets,67,442,253,1,0,196,133,Cody Zeller
9099,44.0,C,1/17/1990,27.0,N,82,BOS,Boston,Celtics,68,157,78,1,0,39,22,Tyler Zeller
10163,33.0,C,9/9/1996,20.0,Y,95,ORL,Orlando,Magic,31,31,10,0,0,5,3,Stephen Zimmerman
10158,16.0,F,2/18/1994,23.0,Y,89,CHI,Chicago,Bulls,55,122,55,99,33,40,31,Paul Zipser
10169,40.0,C,3/17/1997,20.0,Y,105,LAL,Los Angeles,Lakers,47,235,126,3,0,49,32,Ivica Zubac

In [21]:
players.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 517 entries, 10138 to 10169
Data columns (total 17 columns):
jersey_number    493 non-null float64
position         517 non-null object
birthdate        508 non-null object
age              508 non-null float64
rookie           517 non-null object
team_id          517 non-null int64
team_abbr        517 non-null object
team_city        517 non-null object
team_name        517 non-null object
games_played     517 non-null int64
fg2_pt_att       517 non-null int64
fg2_pt_made      517 non-null int64
fg3_pt_att       517 non-null int64
fg3_pt_made      517 non-null int64
ft_att           517 non-null int64
ft_made          517 non-null int64
full_name        517 non-null object
dtypes: float64(2), int64(8), object(7)
memory usage: 92.7+ KB

In [20]:
players.to_csv('./players_dataframe.csv', header=False)